/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import javax.swing.JFrame;

/**
 *
 * @author Jorge A. Santos
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Planet_Earth.jpg"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        getContentPane().add(jButton2);
        jButton2.setBounds(38, 50, 70, 70);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nova_blast.jpg"))); // NOI18N
        jButton3.setText("jButton3");
        getContentPane().add(jButton3);
        jButton3.setBounds(185, 50, 70, 70);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nova_blast.jpg"))); // NOI18N
        jButton4.setText("jButton4");
        getContentPane().add(jButton4);
        jButton4.setBounds(258, 50, 70, 70);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nova_blast.jpg"))); // NOI18N
        jButton5.setText("jButton5");
        getContentPane().add(jButton5);
        jButton5.setBounds(330, 50, 70, 70);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nova_blast.jpg"))); // NOI18N
        jButton6.setText("jButton6");
        getContentPane().add(jButton6);
        jButton6.setBounds(477, 50, 70, 70);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nova_blast.jpg"))); // NOI18N
        jButton7.setText("jButton7");
        getContentPane().add(jButton7);
        jButton7.setBounds(403, 50, 70, 70);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton8.setText("jButton8");
        getContentPane().add(jButton8);
        jButton8.setBounds(550, 50, 70, 70);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton9.setText("jButton9");
        getContentPane().add(jButton9);
        jButton9.setBounds(623, 50, 70, 70);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nova_blast.jpg"))); // NOI18N
        jButton10.setText("jButton10");
        getContentPane().add(jButton10);
        jButton10.setBounds(111, 50, 70, 70);
        getContentPane().add(jButton11);
        jButton11.setBounds(38, 330, 70, 70);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton12.setText("jButton12");
        getContentPane().add(jButton12);
        jButton12.setBounds(696, 50, 70, 70);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton13.setText("jButton13");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(696, 120, 70, 70);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton14.setText("jButton14");
        getContentPane().add(jButton14);
        jButton14.setBounds(403, 190, 70, 70);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton15.setText("jButton15");
        getContentPane().add(jButton15);
        jButton15.setBounds(696, 190, 70, 70);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton16.setText("jButton16");
        getContentPane().add(jButton16);
        jButton16.setBounds(550, 120, 70, 70);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton17.setText("jButton17");
        getContentPane().add(jButton17);
        jButton17.setBounds(623, 190, 70, 70);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton18.setText("jButton18");
        getContentPane().add(jButton18);
        jButton18.setBounds(623, 120, 70, 70);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton19.setText("jButton19");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19);
        jButton19.setBounds(477, 190, 70, 70);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton20.setText("jButton20");
        getContentPane().add(jButton20);
        jButton20.setBounds(111, 120, 70, 70);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton21.setText("jButton21");
        getContentPane().add(jButton21);
        jButton21.setBounds(258, 120, 70, 70);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton22.setText("jButton22");
        getContentPane().add(jButton22);
        jButton22.setBounds(330, 260, 70, 70);

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton23.setText("jButton23");
        getContentPane().add(jButton23);
        jButton23.setBounds(623, 260, 70, 70);

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton24.setText("jButton24");
        getContentPane().add(jButton24);
        jButton24.setBounds(696, 260, 70, 70);

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton25.setText("jButton25");
        getContentPane().add(jButton25);
        jButton25.setBounds(258, 190, 70, 70);

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton26.setText("jButton26");
        getContentPane().add(jButton26);
        jButton26.setBounds(38, 120, 70, 70);

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton27.setText("jButton27");
        getContentPane().add(jButton27);
        jButton27.setBounds(185, 260, 70, 70);

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton28.setText("jButton28");
        getContentPane().add(jButton28);
        jButton28.setBounds(258, 260, 70, 70);

        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton29.setText("jButton29");
        getContentPane().add(jButton29);
        jButton29.setBounds(185, 190, 70, 70);

        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton30.setText("jButton30");
        getContentPane().add(jButton30);
        jButton30.setBounds(477, 120, 70, 70);

        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton31.setText("jButton31");
        getContentPane().add(jButton31);
        jButton31.setBounds(185, 120, 70, 70);

        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton32.setText("jButton32");
        getContentPane().add(jButton32);
        jButton32.setBounds(38, 260, 70, 70);

        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton33.setText("jButton33");
        getContentPane().add(jButton33);
        jButton33.setBounds(403, 260, 70, 70);

        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton34.setText("jButton34");
        getContentPane().add(jButton34);
        jButton34.setBounds(403, 120, 70, 70);

        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton35.setText("jButton35");
        getContentPane().add(jButton35);
        jButton35.setBounds(111, 190, 70, 70);

        jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton36.setText("jButton36");
        getContentPane().add(jButton36);
        jButton36.setBounds(330, 190, 70, 70);

        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton37.setText("jButton37");
        getContentPane().add(jButton37);
        jButton37.setBounds(330, 120, 70, 70);

        jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton38.setText("jButton38");
        getContentPane().add(jButton38);
        jButton38.setBounds(477, 260, 70, 70);

        jButton39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton39.setText("jButton39");
        getContentPane().add(jButton39);
        jButton39.setBounds(38, 190, 70, 70);

        jButton40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton40.setText("jButton40");
        getContentPane().add(jButton40);
        jButton40.setBounds(550, 190, 70, 70);

        jButton41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton41.setText("jButton41");
        getContentPane().add(jButton41);
        jButton41.setBounds(550, 260, 70, 70);

        jButton42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evils.png"))); // NOI18N
        jButton42.setText("jButton42");
        getContentPane().add(jButton42);
        jButton42.setBounds(111, 260, 70, 70);
        getContentPane().add(jButton43);
        jButton43.setBounds(111, 330, 70, 70);
        getContentPane().add(jButton44);
        jButton44.setBounds(696, 330, 70, 70);

        jButton45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton45.setText("jButton45");
        getContentPane().add(jButton45);
        jButton45.setBounds(696, 470, 70, 70);
        getContentPane().add(jButton46);
        jButton46.setBounds(185, 330, 70, 70);
        getContentPane().add(jButton47);
        jButton47.setBounds(403, 330, 70, 70);

        jButton48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton48.setText("jButton48");
        getContentPane().add(jButton48);
        jButton48.setBounds(185, 610, 70, 70);
        getContentPane().add(jButton49);
        jButton49.setBounds(330, 330, 70, 70);

        jButton50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton50.setText("jButton50");
        getContentPane().add(jButton50);
        jButton50.setBounds(403, 540, 70, 70);

        jButton51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton51.setText("jButton51");
        getContentPane().add(jButton51);
        jButton51.setBounds(403, 470, 70, 70);
        getContentPane().add(jButton52);
        jButton52.setBounds(38, 400, 70, 70);
        getContentPane().add(jButton53);
        jButton53.setBounds(623, 330, 70, 70);
        getContentPane().add(jButton54);
        jButton54.setBounds(258, 330, 70, 70);

        jButton55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton55.setText("jButton55");
        getContentPane().add(jButton55);
        jButton55.setBounds(185, 470, 70, 70);
        getContentPane().add(jButton56);
        jButton56.setBounds(550, 330, 70, 70);

        jButton57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton57.setText("jButton57");
        getContentPane().add(jButton57);
        jButton57.setBounds(185, 540, 70, 70);

        jButton58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PumpkinBomb.jpg"))); // NOI18N
        jButton58.setText("jButton58");
        getContentPane().add(jButton58);
        jButton58.setBounds(403, 680, 70, 70);

        jButton59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PumpkinBomb.jpg"))); // NOI18N
        jButton59.setText("jButton59");
        getContentPane().add(jButton59);
        jButton59.setBounds(185, 680, 70, 70);

        jButton60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton60.setText("jButton60");
        getContentPane().add(jButton60);
        jButton60.setBounds(623, 470, 70, 70);

        jButton61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Planet_Earth.jpg"))); // NOI18N
        jButton61.setText("jButton61");
        getContentPane().add(jButton61);
        jButton61.setBounds(38, 680, 70, 70);

        jButton62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton62.setText("jButton62");
        getContentPane().add(jButton62);
        jButton62.setBounds(38, 610, 70, 70);

        jButton63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton63.setText("jButton63");
        getContentPane().add(jButton63);
        jButton63.setBounds(38, 470, 70, 70);

        jButton64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton64.setText("jButton64");
        getContentPane().add(jButton64);
        jButton64.setBounds(38, 540, 70, 70);
        getContentPane().add(jButton65);
        jButton65.setBounds(258, 400, 70, 70);

        jButton66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton66.setText("jButton66");
        getContentPane().add(jButton66);
        jButton66.setBounds(111, 610, 70, 70);
        getContentPane().add(jButton67);
        jButton67.setBounds(403, 400, 70, 70);

        jButton68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton68.setText("jButton68");
        getContentPane().add(jButton68);
        jButton68.setBounds(330, 540, 70, 70);

        jButton69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton69.setText("jButton69");
        getContentPane().add(jButton69);
        jButton69.setBounds(403, 610, 70, 70);
        getContentPane().add(jButton70);
        jButton70.setBounds(111, 400, 70, 70);
        getContentPane().add(jButton71);
        jButton71.setBounds(550, 400, 70, 70);

        jButton72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PumpkinBomb.jpg"))); // NOI18N
        jButton72.setText("jButton72");
        getContentPane().add(jButton72);
        jButton72.setBounds(477, 680, 70, 70);
        getContentPane().add(jButton73);
        jButton73.setBounds(623, 400, 70, 70);

        jButton74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton74.setText("jButton74");
        getContentPane().add(jButton74);
        jButton74.setBounds(111, 470, 70, 70);

        jButton75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton75.setText("jButton75");
        getContentPane().add(jButton75);
        jButton75.setBounds(477, 540, 70, 70);

        jButton76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PumpkinBomb.jpg"))); // NOI18N
        jButton76.setText("jButton76");
        getContentPane().add(jButton76);
        jButton76.setBounds(330, 680, 70, 70);
        getContentPane().add(jButton77);
        jButton77.setBounds(477, 330, 70, 70);

        jButton78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton78.setText("jButton78");
        getContentPane().add(jButton78);
        jButton78.setBounds(477, 610, 70, 70);

        jButton79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton79.setText("jButton79");
        getContentPane().add(jButton79);
        jButton79.setBounds(550, 470, 70, 70);
        getContentPane().add(jButton80);
        jButton80.setBounds(696, 400, 70, 70);

        jButton81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton81.setText("jButton81");
        getContentPane().add(jButton81);
        jButton81.setBounds(258, 540, 70, 70);

        jButton82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PumpkinBomb.jpg"))); // NOI18N
        jButton82.setText("jButton82");
        getContentPane().add(jButton82);
        jButton82.setBounds(258, 680, 70, 70);

        jButton83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton83.setText("jButton83");
        getContentPane().add(jButton83);
        jButton83.setBounds(623, 540, 70, 70);
        getContentPane().add(jButton84);
        jButton84.setBounds(330, 400, 70, 70);

        jButton85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PumpkinBomb.jpg"))); // NOI18N
        jButton85.setText("jButton85");
        getContentPane().add(jButton85);
        jButton85.setBounds(111, 680, 70, 70);

        jButton86.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton86.setText("jButton86");
        getContentPane().add(jButton86);
        jButton86.setBounds(550, 610, 70, 70);

        jButton87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton87.setText("jButton87");
        getContentPane().add(jButton87);
        jButton87.setBounds(696, 540, 70, 70);
        getContentPane().add(jButton88);
        jButton88.setBounds(185, 400, 70, 70);

        jButton89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton89.setText("jButton89");
        getContentPane().add(jButton89);
        jButton89.setBounds(550, 540, 70, 70);

        jButton90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton90.setText("jButton90");
        getContentPane().add(jButton90);
        jButton90.setBounds(330, 610, 70, 70);

        jButton91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton91.setText("jButton91");
        getContentPane().add(jButton91);
        jButton91.setBounds(258, 610, 70, 70);

        jButton92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton92.setText("jButton92");
        getContentPane().add(jButton92);
        jButton92.setBounds(477, 470, 70, 70);

        jButton93.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton93.setText("jButton93");
        getContentPane().add(jButton93);
        jButton93.setBounds(330, 470, 70, 70);
        getContentPane().add(jButton94);
        jButton94.setBounds(477, 400, 70, 70);

        jButton95.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton95.setText("jButton95");
        getContentPane().add(jButton95);
        jButton95.setBounds(111, 540, 70, 70);

        jButton96.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton96.setText("jButton96");
        getContentPane().add(jButton96);
        jButton96.setBounds(258, 470, 70, 70);

        jButton97.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton97.setText("jButton97");
        getContentPane().add(jButton97);
        jButton97.setBounds(623, 610, 70, 70);

        jButton98.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton98.setText("jButton98");
        getContentPane().add(jButton98);
        jButton98.setBounds(623, 680, 70, 70);

        jButton99.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton99.setText("jButton99");
        getContentPane().add(jButton99);
        jButton99.setBounds(696, 610, 70, 70);

        jButton100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton100.setText("jButton100");
        getContentPane().add(jButton100);
        jButton100.setBounds(550, 680, 70, 70);

        jButton101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heroes.png"))); // NOI18N
        jButton101.setText("jButton101");
        getContentPane().add(jButton101);
        jButton101.setBounds(696, 680, 70, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel2KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(800, 680, 70, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Wallpaper-Stratego.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -250, 1920, 1200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jLabel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyPressed

        MenuPrincipal  mp = new MenuPrincipal();
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2KeyPressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
